language: julia

os:
  - osx
  - linux
  - windows

julia:
  - 1.4
  - 1.5
  - nightly

matrix:
  allow_failures:
    - julia: nightly

notifications:
  email: false

after_success:
  - julia -e 'if VERSION >= v"0.7.0-" using Pkg end; cd(Pkg.dir("GNSSSignals")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';
