language: julia

os:
  - osx
  - linux
  - windows

julia:
  - 1.4
  - 1.5
  - nightly

matrix:
  allow_failures:
    - julia: nightly

notifications:
  email: false

after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
