# Constants for the GPS L2 civil signals (L2 CM and L2 CL), PRNs 1-63.
#
# Source: IS-GPS-200N (01-AUG-2022), §3.2.1.4 (L2 CM-code), §3.2.1.5 (L2
# CL-code), §3.3.2.4 (L2 CM-/L2 CL-code generation), and the per-PRN
# initial-state tables 3-IIa (PRNs 1-37) and 3-IIb (PRNs 38-63).
#
# The L2 CM and L2 CL codes are generated by the same degree-27 modular
# (Galois) shift-register generator, clocked at 511.5 kcps and short-cycled
# (reset to the per-PRN initial state) every 10230 chips for CM (20 ms) and
# every 767250 chips for CL (1.5 s). See `gen_l2c_code` in l2c.jl.
#
# The per-PRN initial states below match GNSS-SDR (`GPS_L2C_M_INIT_REG`) and
# PocketSDR (`L2CM_R_init_1` / `L2CL_R_init_1`) exactly; the published End
# Shift Register States from the same ICD tables are cross-checked in
# test/gps/l2c.jl.

# Number of PRN signal numbers supported (IS-GPS-200N Tables 3-IIa/3-IIb).
# The additional sequences for PRNs 159-210 (Table 6-II) are not implemented.
const GPS_L2C_NUM_PRNS = 63

# Code lengths in chips (IS-GPS-200N §3.3.2.4): the CM-code is short-cycled
# after 10230 chips, the CL-code after 767250 chips.
const GPS_L2CM_CODE_LENGTH = 10230
const GPS_L2CL_CODE_LENGTH = 767250

# Chip rate shared by both components (IS-GPS-200N §3.2.1.4/§3.2.1.5).
const GPS_L2C_CODE_FREQUENCY = 511_500Hz

# IS-GPS-200N §3.3.2.4: the maximal code generator polynomial used for both
# the L2 CM- and L2 CL-codes is 1112225171 (octal), of degree 27.
const GPS_L2C_CODE_POLYNOMIAL = 0o1112225171

# Feedback mask for the modular (Galois) right-shift register: the polynomial
# with its X^0 term dropped and shifted down by one (`poly >> 1`). At each
# step the register outputs its least-significant bit, shifts right, and XORs
# this mask back in when the output bit was 1. This is the same mask used by
# PocketSDR (0b100100101001001010100111100) and GNSS-SDR.
const GPS_L2C_FEEDBACK_MASK = UInt32(GPS_L2C_CODE_POLYNOMIAL >> 1)

# Per-PRN initial shift-register states for the L2 CM-code (IS-GPS-200N
# Tables 3-IIa/3-IIb, "L2 CM" column), 9-digit octal, PRNs 1-63.
const GPS_L2CM_INITIAL_STATES = UInt32[
    0o742417664, 0o756014035, 0o002747144, 0o066265724, 0o601403471,
    0o703232733, 0o124510070, 0o617316361, 0o047541621, 0o733031046,
    0o713512145, 0o024437606, 0o021264003, 0o230655351, 0o001314400,
    0o222021506, 0o540264026, 0o205521705, 0o064022144, 0o120161274,
    0o044023533, 0o724744327, 0o045743577, 0o741201660, 0o700274134,
    0o010247261, 0o713433445, 0o737324162, 0o311627434, 0o710452007,
    0o722462133, 0o050172213, 0o500653703, 0o755077436, 0o136717361,
    0o756675453, 0o435506112, 0o771353753, 0o226107701, 0o022025110,
    0o402466344, 0o752566114, 0o702011164, 0o041216771, 0o047457275,
    0o266333164, 0o713167356, 0o060546335, 0o355173035, 0o617201036,
    0o157465571, 0o767360553, 0o023127030, 0o431343777, 0o747317317,
    0o045706125, 0o002744276, 0o060036467, 0o217744147, 0o603340174,
    0o326616775, 0o063240065, 0o111460621,
]

# Per-PRN initial shift-register states for the L2 CL-code (IS-GPS-200N
# Tables 3-IIa/3-IIb, "L2 CL" column), 9-digit octal, PRNs 1-63.
const GPS_L2CL_INITIAL_STATES = UInt32[
    0o624145772, 0o506610362, 0o220360016, 0o710406104, 0o001143345,
    0o053023326, 0o652521276, 0o206124777, 0o015563374, 0o561522076,
    0o023163525, 0o117776450, 0o606516355, 0o003037343, 0o046515565,
    0o671511621, 0o605402220, 0o002576207, 0o525163451, 0o266527765,
    0o006760703, 0o501474556, 0o743747443, 0o615534726, 0o763621420,
    0o720727474, 0o700521043, 0o222567263, 0o132765304, 0o746332245,
    0o102300466, 0o255231716, 0o437661701, 0o717047302, 0o222614207,
    0o561123307, 0o240713073, 0o101232630, 0o132525726, 0o315216367,
    0o377046065, 0o655351360, 0o435776513, 0o744242321, 0o024346717,
    0o562646415, 0o731455342, 0o723352536, 0o000013134, 0o011566642,
    0o475432222, 0o463506741, 0o617127534, 0o026050332, 0o733774235,
    0o751477772, 0o417631550, 0o052247456, 0o560404163, 0o417751005,
    0o004302173, 0o715005045, 0o001154457,
]
