include("b2a_constants.jl")

"""
    BeiDouB2aI{C} <: AbstractBeiDouSignal{C}

BeiDou B2a data signal (the in-phase, data-carrying component of B2a).

BPSK(10)-modulated 10230-chip primary code at 10.23 Mcps on the B2a frequency —
which is the 1176.45 MHz GPS L5 / Galileo E5a carrier, so [`get_band`](@ref)
returns [`L5`](@ref). The data channel carries a fixed 5-bit secondary code
(`00010`, shared across all SVIDs), giving a 5 ms tiered code, and the B-CNAV2
navigation message at 200 symbols/s.

The primary code is the modulo-2 sum of two 13-stage shift registers with the
B2a **data** polynomials (BDS-SIS-ICD-B2a-1.0 §5.2.1, Eq. 5-1): register 1
(`1+x+x⁵+x¹¹+x¹³`) starts all-ones and is reset after 8190 chips; register 2
(`1+x³+x⁵+x⁹+x¹¹+x¹²+x¹³`) starts from a per-SVID value (`B2A_DATA_REG2_INIT`,
ICD Table 5-2). PRNs 1-63 are supported.

# Example
```julia
b2a_i = BeiDouB2aI()
get_code_length(b2a_i)            # 10230
get_secondary_code_length(b2a_i)  # 5
get_band(b2a_i)                   # L5()
```
"""
struct BeiDouB2aI{C<:AbstractMatrix} <: AbstractBeiDouSignal{C}
    codes::C
    lut::SignalLUT    # embedded per-signal LUT, always populated; see `build_signal_lut` / `gen_code!`
end

"""
    BeiDouB2aQ{C, M} <: AbstractBeiDouSignal{C}

BeiDou B2a pilot signal (the quadrature, dataless component of B2a).

BPSK(10)-modulated 10230-chip primary code at 10.23 Mcps on the 1176.45 MHz
carrier (reported as [`L5`](@ref)), overlaid with a per-SVID 100-chip secondary
code for a 100 ms tiered code. As the pilot component it carries no navigation
data, so [`get_data_frequency`](@ref) returns 0 Hz.

The primary code uses the B2a **pilot** polynomials (BDS-SIS-ICD-B2a-1.0
§5.2.1, Eq. 5-2): register 1 `1+x³+x⁶+x⁷+x¹³`, register 2
`1+x+x⁵+x⁷+x⁸+x¹²+x¹³`, with the per-SVID register-2 start values
`B2A_PILOT_REG2_INIT` (ICD Table 5-3). The 100-chip secondary codes are
generated by truncating a length-1021 Weil code (ICD Table 5-4) and are exposed
via [`get_secondary_code`](@ref) as a [`PerPRNSecondaryCode`](@ref). PRNs 1-63.

# Example
```julia
b2a_q = BeiDouB2aQ()
get_code_length(b2a_q)            # 10230
get_secondary_code_length(b2a_q)  # 100
get_data_frequency(b2a_q)         # 0 Hz
```
"""
struct BeiDouB2aQ{C<:AbstractMatrix, M<:AbstractMatrix} <: AbstractBeiDouSignal{C}
    codes::C
    secondary_codes::M    # 100 × 63 Int8 ±1 matrix, exposed via PerPRNSecondaryCode
    lut::SignalLUT        # embedded per-signal LUT, always populated; see `build_signal_lut` / `gen_code!`
end

# Data: g1 = 1+x+x⁵+x¹¹+x¹³ ; g2 = 1+x³+x⁵+x⁹+x¹¹+x¹²+x¹³
const B2A_DATA_G1_FEEDBACK = (1, 5, 11, 13)
const B2A_DATA_G2_FEEDBACK = (3, 5, 9, 11, 12, 13)
# Pilot: g1 = 1+x³+x⁶+x⁷+x¹³ ; g2 = 1+x+x⁵+x⁷+x⁸+x¹²+x¹³
const B2A_PILOT_G1_FEEDBACK = (3, 6, 7, 13)
const B2A_PILOT_G2_FEEDBACK = (1, 5, 7, 8, 12, 13)
const B2A_CODE_LENGTH = 10230
const B2A_RESET1_AT = 8190
const B2A_NUM_PRNS = 63
const B2A_SECONDARY_WEIL_LENGTH = 1021    # Legendre length for the pilot secondary
const B2A_SECONDARY_LENGTH = 100

# Build the 10230 × 63 primary-code matrix for the given feedback polynomials
# and per-SVID register-2 start values.
function _read_beidou_b2a_codes(g1_fb, g2_fb, reg2_init)
    init1 = fill(Int8(1), 13)
    codes = Matrix{Int8}(undef, B2A_CODE_LENGTH, B2A_NUM_PRNS)
    for prn = 1:B2A_NUM_PRNS
        init2 = _beidou_state(reg2_init[prn])
        codes[:, prn] = _beidou_gold_code(
            13, B2A_CODE_LENGTH, g1_fb, g2_fb, (13,), (13,), init1, init2, B2A_RESET1_AT,
        )
    end
    codes
end

read_beidou_b2a_i_codes() =
    _read_beidou_b2a_codes(B2A_DATA_G1_FEEDBACK, B2A_DATA_G2_FEEDBACK, B2A_DATA_REG2_INIT)
read_beidou_b2a_q_codes() =
    _read_beidou_b2a_codes(B2A_PILOT_G1_FEEDBACK, B2A_PILOT_G2_FEEDBACK, B2A_PILOT_REG2_INIT)

# Build the 100 × 63 B2a pilot secondary matrix (truncated length-1021 Weil codes).
function _build_beidou_b2a_secondary()
    L = _beidou_legendre(B2A_SECONDARY_WEIL_LENGTH)
    codes = Matrix{Int8}(undef, B2A_SECONDARY_LENGTH, B2A_NUM_PRNS)
    for prn = 1:B2A_NUM_PRNS
        w, p = B2A_PILOT_SECONDARY_WP[prn]
        codes[:, prn] = _beidou_weil_code(B2A_SECONDARY_WEIL_LENGTH, B2A_SECONDARY_LENGTH, w, p, L)
    end
    codes
end

function BeiDouB2aI()
    codes = widen_codes_to_storage(read_beidou_b2a_i_codes())
    lut = build_signal_lut(get_modulation(BeiDouB2aI), codes, _beidou_b2a_i_secondary_code())
    BeiDouB2aI(codes, lut)
end

function BeiDouB2aQ()
    codes = widen_codes_to_storage(read_beidou_b2a_q_codes())
    secondary = _build_beidou_b2a_secondary()
    # The 100-chip per-SVID secondary is too long to bake (100·10230 > typemax(Int16)),
    # so it stays residual in the SignalLUT and is applied per primary period at gen time.
    lut = build_signal_lut(get_modulation(BeiDouB2aQ), codes, PerPRNSecondaryCode(secondary))
    BeiDouB2aQ(codes, secondary, lut)
end

# Shared interface.

get_modulation(::Type{<:BeiDouB2aI}) = LOC()
@inline get_modulation(::BeiDouB2aI) = LOC()
get_modulation(::Type{<:BeiDouB2aQ}) = LOC()
@inline get_modulation(::BeiDouB2aQ) = LOC()

"""
$(SIGNATURES)

Get the band the signal is transmitted on.

BeiDou B2a shares the 1176.45 MHz GPS L5 / Galileo E5a carrier, so this returns
[`L5`](@ref) — band identity is by RF, not by ICD label.
"""
@inline get_band(::Type{<:BeiDouB2aI}) = L5()
@inline get_band(::Type{<:BeiDouB2aQ}) = L5()

"""
$(SIGNATURES)

Get the human-readable signal name.
"""
get_signal_name(::BeiDouB2aI) = "BeiDou B2a data"
get_signal_name(::BeiDouB2aQ) = "BeiDou B2a pilot"

"""
$(SIGNATURES)

Get the code length for BeiDou B2a (10230 chips, both components).
"""
@inline get_code_length(::Type{<:BeiDouB2aI}) = B2A_CODE_LENGTH
@inline get_code_length(::Type{<:BeiDouB2aQ}) = B2A_CODE_LENGTH

"""
$(SIGNATURES)

Get the code chipping rate for BeiDou B2a (10.23 MHz, both components).
"""
@inline get_code_frequency(::Type{<:BeiDouB2aI}) = 10_230_000Hz
@inline get_code_frequency(::Type{<:BeiDouB2aQ}) = 10_230_000Hz

"""
$(SIGNATURES)

Get the data symbol rate for BeiDou B2a data (B-CNAV2, 200 symbols/s).

# Returns
- `Frequency`: 200 Hz
"""
@inline get_data_frequency(::Type{<:BeiDouB2aI}) = 200Hz

"""
$(SIGNATURES)

Get the data symbol rate for BeiDou B2a pilot (dataless).

# Returns
- `Frequency`: 0 Hz
"""
@inline get_data_frequency(::Type{<:BeiDouB2aQ}) = 0Hz

"""
$(SIGNATURES)

Get the secondary code for BeiDou B2a data.

A fixed 5-bit sequence `00010` (BDS-SIS-ICD-B2a-1.0 §5.2.2), shared across all
SVIDs, mapped 0 → -1, 1 → +1 — a 5 ms tiered code.

# Returns
- [`SharedSecondaryCode`](@ref) of length 5
"""
@inline get_secondary_code(::BeiDouB2aI) = _beidou_b2a_i_secondary_code()

# Fixed 5-bit data secondary (00010), shared across SVIDs. Factored out so the constructor can
# build the embedded `SignalLUT` before an instance exists.
@inline _beidou_b2a_i_secondary_code() =
    SharedSecondaryCode(Int8(-1), Int8(-1), Int8(-1), Int8(1), Int8(-1))

"""
$(SIGNATURES)

Get the secondary code for BeiDou B2a pilot.

Each SVID overlays its primary code with a 100-chip sequence obtained by
truncating a length-1021 Weil code (BDS-SIS-ICD-B2a-1.0 §5.2.2, Table 5-4),
giving a 100 ms tiered code.

# Returns
- [`PerPRNSecondaryCode`](@ref) wrapping the 100 × 63 secondary matrix
"""
@inline get_secondary_code(s::BeiDouB2aQ) = PerPRNSecondaryCode(s.secondary_codes)
