"""
    GalileoE1C{C} <: AbstractGNSSSignal{C}

Galileo E1C signal (the pilot, dataless component of Galileo E1 OS).

CBOC(6,1,1/11) modulation with a 4092-chip primary code at 1.023 Mcps,
overlaid by the 25-chip CS25 secondary code (one chip per 4 ms primary
period, giving a 100 ms tiered code). Transmitted on the E1 band — which
shares the L1 carrier at 1575.42 MHz, so [`get_band`](@ref) returns
[`L1`](@ref) here.

E1C differs from [`GalileoE1B`](@ref) in three ways:

- It is a *pilot*: it carries no navigation data
  ([`get_data_frequency`](@ref) returns `0 Hz`).
- It has a 25-chip secondary code (CS25), where E1B has none.
- Its CBOC uses the BOC(6,1) component in *anti-phase* — CBOC(−) — per the
  Galileo OS SIS ICD §2.3.3, where E1-B uses CBOC(+).

The struct caches an element-wise negated primary-code matrix so that
`gen_code!` can hoist the per-secondary-chip sign multiply out of the inner
loop (the same trick used for [`GPSL5I`](@ref)).

# Example
```julia
e1c = GalileoE1C()
get_code_length(e1c)            # 4092
get_secondary_code_length(e1c)  # 25
get_band(e1c)                   # L1()
```
"""
struct GalileoE1C{C<:AbstractMatrix} <: AbstractGNSSSignal{C}
    codes::C
    lut::SignalLUT    # embedded per-signal LUT, always populated; see `build_signal_lut` / `gen_code!`
end

get_modulation(::Type{<:GalileoE1C}) = CBOC(BOCsin(1, 1), BOCsin(6, 1), 10 / 11, -1)
@inline get_modulation(::GalileoE1C) = CBOC(BOCsin(1, 1), BOCsin(6, 1), 10 / 11, -1)

"""
$(SIGNATURES)

Get the band the signal is transmitted on.

Galileo E1 shares the L1 carrier frequency (1575.42 MHz), so this returns
[`L1`](@ref) — band identity is by RF, not by ICD label.

# Examples
```julia-repl
julia> get_band(GalileoE1C())
L1()
```
"""
@inline get_band(::GalileoE1C) = L1()

"""
$(SIGNATURES)

Get the human-readable signal name.

# Examples
```julia-repl
julia> get_signal_name(GalileoE1C())
"Galileo E1C"
```
"""
get_signal_name(::GalileoE1C) = "Galileo E1C"

function read_galileo_e1c_codes()
    read_in_codes(
        Int8,
        joinpath(dirname(pathof(GNSSSignals)), "..", "data", "codes_galileo_e1c.bin"),
        50,
        4092,
    )
end

function GalileoE1C()
    codes = widen_codes_to_storage(read_galileo_e1c_codes())
    lut = build_signal_lut(get_modulation(GalileoE1C), codes, galileo_e1c_secondary_code())
    GalileoE1C(codes, lut)
end

"""
$(SIGNATURES)

Get the code length for Galileo E1C.

# Returns
- `Int`: 4092 chips

# Examples
```julia-repl
julia> get_code_length(GalileoE1C())
4092
```
"""
@inline function get_code_length(::GalileoE1C)
    4092
end

# CS25 = "0011100000001010110110010", bit 1 → +1, bit 0 → -1. Shared by
# both the full-CBOC and BOC(1,1)-approximation E1C types.
@inline function galileo_e1c_secondary_code()
    SharedSecondaryCode(
        Int8(-1), Int8(-1), Int8(1), Int8(1), Int8(1),
        Int8(-1), Int8(-1), Int8(-1), Int8(-1), Int8(-1),
        Int8(-1), Int8(-1), Int8(1), Int8(-1), Int8(1),
        Int8(-1), Int8(1), Int8(1), Int8(-1), Int8(1),
        Int8(1), Int8(-1), Int8(-1), Int8(1), Int8(-1),
    )
end

"""
$(SIGNATURES)

Get the secondary (CS25) code for Galileo E1C.

CS25 is shared across all PRNs: every primary code period (4 ms) is XOR'd
with one chip of the 25-bit sequence `0011100000001010110110010` (Galileo
OS SIS ICD §2.3.4), mapped to `±1` with bit `1 → +1`. This matches the
primary-code sign convention, so the combined primary × secondary ranging
code is bit-identical to the one generated by GNSS-SDR.

# Returns
- [`SharedSecondaryCode`](@ref) of length 25

# Examples
```julia-repl
julia> get_secondary_code(GalileoE1C())
SharedSecondaryCode{25, Int8}((-1, -1, 1, 1, 1, -1, -1, -1, -1, -1, -1, -1, 1, -1, 1, -1, 1, 1, -1, 1, 1, -1, -1, 1, -1))
```
"""
@inline get_secondary_code(::GalileoE1C) = galileo_e1c_secondary_code()

"""
$(SIGNATURES)

Get the code chipping rate for Galileo E1C.

# Returns
- `Frequency`: 1.023 MHz

# Examples
```julia-repl
julia> get_code_frequency(GalileoE1C())
1023000 Hz
```
"""
@inline function get_code_frequency(::GalileoE1C)
    1023_000Hz
end

"""
$(SIGNATURES)

Get the data bit rate for Galileo E1C.

E1C is the pilot (dataless) component, so this is `0 Hz`.

# Returns
- `Frequency`: 0 Hz

# Examples
```julia-repl
julia> get_data_frequency(GalileoE1C())
0 Hz
```
"""
@inline function get_data_frequency(::GalileoE1C)
    0Hz
end

"""
    GalileoE1C_BOC11{C} <: AbstractGNSSSignal{C}

BOC(1,1) approximation of Galileo E1C (the pilot component of Galileo E1
OS).

Galileo E1C is specified as CBOC(6,1,1/11) — a Float32 weighted sum of
BOC(1,1) and BOC(6,1) requiring fs ≥ 2 · 6 · 1.023 MHz to fully sample.
Many software receivers substitute a pure BOC(1,1) replica because (a) the
BOC(6,1) component carries only 1/11 of the signal power, so the
correlation loss is ≈ 0.45 dB, and (b) BOC(1,1) needs only
fs ≥ 2 · 1.023 MHz, allowing lower sampling rates and Int16 output.
PocketSDR, for example, uses this substitution for E1C by default (see
`gen_code_E1C` in `sdr_code.c`).

Use this type when you want the lower sampling-rate, Int16-output variant;
use [`GalileoE1C`](@ref) for the full CBOC spec output (Float32).

Primary code, code length, secondary code (CS25), code frequency, data
rate, and band are identical to [`GalileoE1C`](@ref); only `get_modulation`
differs.

# Example
```julia
e1c = GalileoE1C_BOC11()
get_modulation(e1c)    # BOCsin(1, 1)
get_code_length(e1c)   # 4092
```
"""
struct GalileoE1C_BOC11{C<:AbstractMatrix} <: AbstractGNSSSignal{C}
    codes::C
    lut::SignalLUT    # embedded per-signal LUT, always populated; see `build_signal_lut` / `gen_code!`
end

get_modulation(::Type{<:GalileoE1C_BOC11}) = BOCsin(1, 1)
@inline get_modulation(::GalileoE1C_BOC11) = BOCsin(1, 1)

@inline get_band(::GalileoE1C_BOC11) = L1()
get_signal_name(::GalileoE1C_BOC11) = "Galileo E1C (BOC(1,1) approximation)"

function GalileoE1C_BOC11()
    codes = widen_codes_to_storage(read_galileo_e1c_codes())
    lut = build_signal_lut(get_modulation(GalileoE1C_BOC11), codes, galileo_e1c_secondary_code())
    GalileoE1C_BOC11(codes, lut)
end

@inline get_code_length(::GalileoE1C_BOC11) = 4092
@inline get_secondary_code(::GalileoE1C_BOC11) = galileo_e1c_secondary_code()
@inline get_code_frequency(::GalileoE1C_BOC11) = 1023_000Hz
@inline get_data_frequency(::GalileoE1C_BOC11) = 0Hz
